development:
  adapter: postgresql
  database: dev_bartinder_database
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: test_bartinder_database
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: prod_bartinder_database
  pool: 5
  timeout: 5000
